[package]
name = "mtg-commander-suggestions"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
clap = { version = "4.0.30", features = ["derive", "wrap_help"] }
color-eyre = "0.6.2"
csv = "1.1.6"
mongodb = "2.3.1"
scryfall = { version = "0.10.0", features = ["bulk_caching"], path = "scryfall-rs" }
serde = "1.0.151"
tokio = "1.23.0"

[dev-dependencies]
serde_json = "1.0.91"
