[package]
name = "mtg-commander-suggestions"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
clap = { version = "4.1.13", features = ["derive", "wrap_help"] }
color-eyre = "0.6.2"
csv = "1.2.1"
futures = "0.3.24"
mongodb = "2.4.0"
scryfall = { version = "0.11.1", features = ["bulk_caching"], path = "scryfall-rs" }
serde = "1.0.158"
thirtyfour = "0.31.0"
tokio = "1.26.0"

[dev-dependencies]
serde_json = "1.0.94"
