[package]
name = "mtg-commander-suggestions"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
clap = { version = "4.3.0", features = ["derive", "wrap_help"] }
color-eyre = "0.6.2"
csv = "1.2.1"
mongodb = "2.5.0"
scryfall = { version = "0.10.0", features = ["bulk_caching"], path = "scryfall-rs" }
serde = "1.0.163"
tokio = "1.28.1"

[dev-dependencies]
serde_json = "1.0.96"
