[package]
name = "mtg-commander-suggestions"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
clap = { version = "3.1.0", features = ["derive", "wrap_help"] }
color-eyre = "0.6.0"
csv = "1.1.6"
mongodb = "2.1.0"
scryfall = { version = "0.10.0", features = ["bulk_caching"], path = "scryfall-rs" }
serde = "1.0.136"
tokio = "1.17.0"

[dev-dependencies]
serde_json = "1.0.79"
