name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --locked
      
    - uses: extractions/setup-just@v1
      
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      
    - name: Integration tests
      run: just test
    
